name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/' # Change this to the directory with your website files
        api_location: 'api'
        app_artifact_location: '/' # Change this to the directory containing your HTML file
        configuration: 'production'
